#!/usr/bin/env node
// Bakes propertyConfig.seo (from site-data.js) into the <!-- SEO:START -->
// ... <!-- SEO:END --> block in index.html as static <title>, meta
// description, canonical, Open Graph and Twitter Card tags. Also (re)writes
// sitemap.xml at the repo root from the same seo.siteUrl.
//
// Why this exists: link-preview bots (Facebook, LINE, WhatsApp, X,
// LinkedIn, ...) fetch raw HTML and don't execute JavaScript, so SEO tags
// that matter for social sharing can't be set by script.js at runtime the
// way the rest of the page's property-specific content is. This script is
// the one place that writes those tags into index.html, so reusing the
// template for a new property still only means editing site-data.js.
//
// Usage: node scripts/sync-seo.js
// Run after editing the `seo` block in site-data.js, before deploying.
//
// No npm dependencies — uses only Node's built-in fs/path/vm modules.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const SITE_DATA_PATH = path.join(ROOT, "site-data.js");
const INDEX_HTML_PATH = path.join(ROOT, "index.html");
const SITEMAP_PATH = path.join(ROOT, "sitemap.xml");

const START_MARKER = "<!-- SEO:START (generated by `node scripts/sync-seo.js` from propertyConfig.seo in site-data.js — do not edit by hand) -->";
const END_MARKER = "<!-- SEO:END -->";

// site-data.js assigns to `window.propertyConfig` for the browser — run it
// in a throwaway sandbox with a fake `window` so we can read that value
// from Node without turning site-data.js into a CommonJS module.
function loadPropertyConfig() {
    const source = fs.readFileSync(SITE_DATA_PATH, "utf8");
    const sandbox = { window: {} };
    vm.createContext(sandbox);
    vm.runInContext(source, sandbox, { filename: SITE_DATA_PATH });

    if (!sandbox.window.propertyConfig) {
        throw new Error("site-data.js did not set window.propertyConfig — aborting.");
    }
    return sandbox.window.propertyConfig;
}

function getText(value, lang) {
    if (typeof value === "string") return value;
    return (value && (value[lang] || value.en)) || "";
}

function escapeHtml(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");
}

function toAbsoluteUrl(siteUrl, imagePath) {
    if (!imagePath) return "";
    if (/^https?:\/\//i.test(imagePath)) return imagePath;
    if (!siteUrl) return imagePath;
    return `${siteUrl}/${imagePath.replace(/^\/+/, "")}`;
}

function buildSeoBlock(config) {
    const seo = config.seo || {};
    const lang = "en";

    const title = getText(seo.title, lang) || `${getText(config.name, lang)} — ${getText(config.location, lang)}`;
    const description = getText(seo.description, lang) || getText(config.heroDescription, lang);
    const siteUrl = (seo.siteUrl || "").replace(/\/+$/, "");
    const image = toAbsoluteUrl(siteUrl, seo.ogImage || config.heroImage || "");
    const twitterHandle = seo.twitterHandle || "";

    const lines = [];
    lines.push(`<title>${escapeHtml(title)}</title>`);
    lines.push("");
    lines.push(`<meta name="description" content="${escapeHtml(description)}">`);

    if (siteUrl) {
        lines.push("");
        lines.push(`<link rel="canonical" href="${escapeHtml(siteUrl)}/">`);
    }

    lines.push("");
    lines.push(`<meta property="og:type" content="website">`);
    lines.push(`<meta property="og:title" content="${escapeHtml(title)}">`);
    lines.push(`<meta property="og:description" content="${escapeHtml(description)}">`);
    if (image) lines.push(`<meta property="og:image" content="${escapeHtml(image)}">`);
    if (siteUrl) lines.push(`<meta property="og:url" content="${escapeHtml(siteUrl)}/">`);

    lines.push("");
    lines.push(`<meta name="twitter:card" content="summary_large_image">`);
    lines.push(`<meta name="twitter:title" content="${escapeHtml(title)}">`);
    lines.push(`<meta name="twitter:description" content="${escapeHtml(description)}">`);
    if (image) lines.push(`<meta name="twitter:image" content="${escapeHtml(image)}">`);
    if (twitterHandle) lines.push(`<meta name="twitter:site" content="${escapeHtml(twitterHandle)}">`);

    return lines.join("\n");
}

function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// sitemap.xml requires absolute <loc> URLs, so there's nothing valid to list
// until seo.siteUrl is set — an empty <urlset> is still well-formed and
// harmless in the meantime. Once siteUrl is set, re-running this script
// fills in the homepage entry automatically.
function buildSitemapXml(config) {
    const siteUrl = ((config.seo && config.seo.siteUrl) || "").replace(/\/+$/, "");

    if (!siteUrl) {
        return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>\n';
    }

    return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n    <url>\n        <loc>${escapeHtml(siteUrl)}/</loc>\n    </url>\n</urlset>\n`;
}

function syncIndexHtml(config) {
    const seoBlock = buildSeoBlock(config);

    const html = fs.readFileSync(INDEX_HTML_PATH, "utf8");
    const pattern = new RegExp(`${escapeRegExp(START_MARKER)}[\\s\\S]*?${escapeRegExp(END_MARKER)}`);

    if (!pattern.test(html)) {
        throw new Error(`Could not find the SEO:START/SEO:END block in ${INDEX_HTML_PATH}`);
    }

    const indentedBlock = seoBlock.split("\n").map(line => line ? `    ${line}` : "").join("\n");
    const replacement = `${START_MARKER}\n${indentedBlock}\n    ${END_MARKER}`;
    const updated = html.replace(pattern, replacement);

    if (updated === html) {
        console.log("index.html SEO block already up to date.");
        return;
    }

    fs.writeFileSync(INDEX_HTML_PATH, updated, "utf8");
    console.log("index.html SEO block updated from site-data.js.");
}

function syncSitemap(config) {
    const sitemap = buildSitemapXml(config);
    const existing = fs.existsSync(SITEMAP_PATH) ? fs.readFileSync(SITEMAP_PATH, "utf8") : null;

    if (existing === sitemap) {
        console.log("sitemap.xml already up to date.");
        return;
    }

    fs.writeFileSync(SITEMAP_PATH, sitemap, "utf8");
    console.log("sitemap.xml updated from site-data.js.");
}

function main() {
    const config = loadPropertyConfig();
    syncIndexHtml(config);
    syncSitemap(config);
}

main();
